from mazegenerator.mazegenerator import MazeGenerator

MAZE_WIDTH = 10
MAZE_HEIGHT = 10


# MARK: cells_to_grid
def _cells_to_grid(maze: list[list[int]]) -> list[list[int]]:
    """Is converting the maze from a 2D list in a Bitmask, so the
    frontendis able to render it.

    Args:
        maze (list): Its a 2D list of the maze generated by the Mazegenerator.

    Returns:
        list: A 2D list representing the maze as a grid of 0s and 1s.
    """
    height = len(maze)
    width = len(maze[0])

    NORTH, EAST, SOUTH, WEST = 1, 2, 4, 8

    rows = height * 2 + 1
    cols = width * 2 + 1
    grid: list[list[int]] = [[1] * cols for _ in range(rows)]

    for y in range(height):
        for x in range(width):
            wall = maze[y][x]
            gr = 2 * y + 1
            gc = 2 * x + 1
            grid[gr][gc] = 0  # Cell is open
            if not wall & NORTH:
                grid[gr - 1][gc] = 0  # Northwall is open
            if not wall & EAST:
                grid[gr][gc + 1] = 0  # Eastwall is open
            if not wall & SOUTH:
                grid[gr + 1][gc] = 0  # Southwall is open
            if not wall & WEST:
                grid[gr][gc - 1] = 0  # Westwall is open

    return grid


# MARK: build_maze
def build_maze(seed: int = 0) -> list[list[int]]:
    """Is creating a new maze with the provided dimensions and the seed.

    Args:
        seed (int, optional): The seed is a random number, which is used
                              to genarate the same maze. Defaults to 0.

    Returns:
        list: A 2D list representing the maze as a grid.
    """
    generator = MazeGenerator(
        size=(MAZE_WIDTH, MAZE_HEIGHT),
        entry_cell=(0, 0),
        exit_cell=(MAZE_WIDTH - 1, MAZE_HEIGHT - 1),
        perfect=False,
        seed=seed,
    )
    return _cells_to_grid(generator.maze)
